-- Seed data for forms
-- Generated: 2025-12-11T08:34:02.711Z

INSERT INTO public.forms (id, name, category, period, description, structure, listen_for, key_works)
VALUES
  ('symphony', 'Symphony', 'Orchestral', 'Classical onwards', 'A large-scale orchestral work, typically in four movements, representing the pinnacle of orchestral composition.', '[{"movement":1,"typical":"Fast (Allegro)","form":"Sonata form","character":"Dramatic introduction of themes"},{"movement":2,"typical":"Slow (Adagio/Andante)","form":"Various (ABA, Theme & Variations)","character":"Lyrical, expressive"},{"movement":3,"typical":"Dance (Minuet/Scherzo)","form":"Minuet and Trio or Scherzo","character":"Lighter, rhythmic"},{"movement":4,"typical":"Fast (Allegro/Presto)","form":"Sonata or Rondo","character":"Triumphant conclusion"}]'::jsonb, '{"The development of themes across movements","Contrast between movement characters","The orchestra working as one unified instrument"}', '[{"composer":"Beethoven","work":"Symphony No. 5","why":"The archetypal symphony—from struggle to triumph"},{"composer":"Mozart","work":"Symphony No. 40","why":"Perfect Classical balance with Romantic intensity"},{"composer":"Brahms","work":"Symphony No. 4","why":"Masterful synthesis of form and emotion"}]'::jsonb),
  ('concerto', 'Concerto', 'Orchestral', 'Baroque onwards', 'A work featuring a solo instrument (or group) in dialogue with an orchestra, showcasing virtuosity and interplay.', '[{"movement":1,"typical":"Fast (Allegro)","form":"Modified sonata form with cadenza","character":"Dramatic, virtuosic"},{"movement":2,"typical":"Slow","form":"Various","character":"Lyrical, intimate"},{"movement":3,"typical":"Fast","form":"Rondo or sonata-rondo","character":"Brilliant, conclusive"}]'::jsonb, '{"The conversation between soloist and orchestra","The cadenza—the soloist's virtuosic showcase","How the soloist leads or responds to the orchestra"}', '[{"composer":"Tchaikovsky","work":"Piano Concerto No. 1","why":"Grand Romantic virtuosity at its finest"},{"composer":"Mendelssohn","work":"Violin Concerto","why":"Seamless fusion of soloist and orchestra"},{"composer":"Bach","work":"Brandenburg Concertos","why":"The Baroque concerto grosso perfected"}]'::jsonb),
  ('sonata', 'Sonata', 'Chamber', 'Classical onwards', 'A multi-movement work for solo piano or piano with one other instrument, exploring the full range of the instrument(s).', '[{"movement":1,"typical":"Fast","form":"Sonata form","character":"Thematic development"},{"movement":2,"typical":"Slow","form":"Various","character":"Lyrical"},{"movement":3,"typical":"Fast","form":"Rondo or Sonata","character":"Conclusive"}]'::jsonb, '{"Sonata form's exposition, development, and recapitulation","The relationship between themes","How the instrument's full capabilities are explored"}', '[{"composer":"Beethoven","work":"Piano Sonata No. 14 ''Moonlight''","why":"Revolutionary structure and emotional depth"},{"composer":"Mozart","work":"Piano Sonata No. 11 ''Alla Turca''","why":"Classical elegance with a famous finale"},{"composer":"Chopin","work":"Piano Sonata No. 2","why":"Contains the iconic Funeral March"}]'::jsonb),
  ('fugue', 'Fugue', 'Contrapuntal', 'Baroque (peak)', 'A complex composition where a theme (subject) is introduced and then imitated by multiple voices in counterpoint.', '[{"section":"Exposition","description":"Subject introduced in each voice in turn"},{"section":"Episodes","description":"Development passages linking subject entries"},{"section":"Middle Entries","description":"Subject in related keys"},{"section":"Final Entries","description":"Return to home key, often with stretto"}]'::jsonb, '{"The subject's first entry and subsequent imitations","How voices weave around each other","The building complexity as more voices join"}', '[{"composer":"Bach","work":"The Well-Tempered Clavier","why":"48 fugues in all 24 keys—the Bible of fugue"},{"composer":"Bach","work":"The Art of Fugue","why":"The ultimate exploration of fugal technique"},{"composer":"Beethoven","work":"Grosse Fuge","why":"Fugue pushed to Romantic extremes"}]'::jsonb),
  ('opera', 'Opera', 'Vocal/Theatrical', 'Baroque onwards', 'A dramatic work combining music, singing, and theatrical staging to tell a story.', '[{"component":"Overture","description":"Orchestral introduction setting the mood"},{"component":"Recitative","description":"Speech-like singing advancing the plot"},{"component":"Aria","description":"Solo songs expressing emotion"},{"component":"Ensemble","description":"Multiple singers together"},{"component":"Chorus","description":"Full choir commenting or participating"}]'::jsonb, '{"How music reflects character emotions","The contrast between recitative and aria","The orchestra's role in creating atmosphere"}', '[{"composer":"Mozart","work":"The Marriage of Figaro","why":"Perfect fusion of comedy and human truth"},{"composer":"Verdi","work":"La Traviata","why":"The ultimate Romantic tragedy"},{"composer":"Wagner","work":"Tristan und Isolde","why":"Revolutionary harmony serving drama"}]'::jsonb),
  ('string-quartet', 'String Quartet', 'Chamber', 'Classical onwards', 'Music for two violins, viola, and cello—four equal voices in intimate conversation.', '[{"movement":1,"typical":"Fast","form":"Sonata form","character":"Intellectual dialogue"},{"movement":2,"typical":"Slow","form":"Various","character":"Lyrical intimacy"},{"movement":3,"typical":"Scherzo/Minuet","form":"Scherzo and Trio","character":"Playful"},{"movement":4,"typical":"Fast","form":"Various","character":"Conclusive energy"}]'::jsonb, '{"Four distinct voices conversing as equals","No place to hide—every note matters","The interplay and handoffs between instruments"}', '[{"composer":"Beethoven","work":"String Quartet Op. 131","why":"Seven movements of profound expression"},{"composer":"Haydn","work":"Op. 76 Quartets","why":"The inventor at his peak"},{"composer":"Debussy","work":"String Quartet in G minor","why":"Impressionism in intimate form"}]'::jsonb),
  ('ballet', 'Ballet', 'Theatrical', 'Romantic onwards', 'Music composed for dance performance, often telling a story through purely orchestral means.', '[{"component":"Suite","description":"Collection of dances forming the work"},{"component":"Pas de deux","description":"Featured duet"},{"component":"Variations","description":"Solo showcase dances"},{"component":"Divertissements","description":"Entertaining interludes"}]'::jsonb, '{"How music suggests movement and gesture","Character themes and their transformations","The drama told purely through sound"}', '[{"composer":"Tchaikovsky","work":"Swan Lake","why":"The quintessential Romantic ballet"},{"composer":"Stravinsky","work":"The Rite of Spring","why":"Ballet as modernist revolution"},{"composer":"Prokofiev","work":"Romeo and Juliet","why":"Narrative power through music"}]'::jsonb),
  ('prelude', 'Prelude', 'Solo/Short Form', 'Baroque onwards', 'Originally an introductory piece, later a standalone short composition capturing a single mood or idea.', '[{"aspect":"Form","description":"Free—no fixed structure"},{"aspect":"Length","description":"Usually short (1-5 minutes)"},{"aspect":"Character","description":"Unified mood or technical focus"}]'::jsonb, '{"The single mood or atmosphere created","How much expression fits in small space","Technical challenges disguised as music"}', '[{"composer":"Chopin","work":"24 Preludes, Op. 28","why":"All 24 keys in miniature masterpieces"},{"composer":"Debussy","work":"Préludes","why":"Impressionistic sound paintings"},{"composer":"Bach","work":"Preludes from WTC","why":"Baroque keyboard idioms explored"}]'::jsonb),
  ('nocturne', 'Nocturne', 'Solo/Short Form', 'Romantic', 'A dreamy, lyrical piano piece evoking the night, characterized by singing melodies over arpeggiated accompaniment.', '[{"aspect":"Form","description":"Usually ABA (ternary)"},{"aspect":"Texture","description":"Melody over broken-chord accompaniment"},{"aspect":"Character","description":"Expressive, introspective, ornamental"}]'::jsonb, '{"The 'singing' right-hand melody","The flowing left-hand accompaniment","Expressive ornamentation and rubato"}', '[{"composer":"Chopin","work":"Nocturne Op. 9 No. 2","why":"The definitive nocturne"},{"composer":"Chopin","work":"Nocturne Op. 48 No. 1","why":"Drama within the dreamscape"},{"composer":"Field","work":"Nocturnes","why":"The inventor of the form"}]'::jsonb),
  ('requiem', 'Requiem', 'Choral', 'All periods', 'A musical setting of the Mass for the Dead, combining profound spiritual texts with powerful music.', '[{"section":"Introit","text":"Requiem aeternam (Eternal rest)"},{"section":"Kyrie","text":"Kyrie eleison (Lord have mercy)"},{"section":"Dies Irae","text":"Day of Wrath—the dramatic centerpiece"},{"section":"Sanctus","text":"Holy, holy, holy"},{"section":"Agnus Dei","text":"Lamb of God"},{"section":"Lux Aeterna","text":"Eternal light"}]'::jsonb, '{"The Dies Irae's terrifying drama","Contrast between wrath and peace","How each composer interprets mortality"}', '[{"composer":"Mozart","work":"Requiem in D minor","why":"Unfinished masterpiece of dramatic power"},{"composer":"Verdi","work":"Requiem","why":"Operatic grandeur meets sacred text"},{"composer":"Brahms","work":"German Requiem","why":"Personal, humanistic approach"}]'::jsonb),
  ('theme-variations', 'Theme and Variations', 'Form', 'All periods', 'A theme is presented, then transformed through successive variations that alter melody, harmony, rhythm, or character.', '[{"section":"Theme","description":"Original melody stated clearly"},{"section":"Variations","description":"Progressive transformations"},{"section":"Finale","description":"Often culminating variation or return to theme"}]'::jsonb, '{"The original theme that everything grows from","How each variation transforms the theme","The unity beneath the diversity"}', '[{"composer":"Bach","work":"Goldberg Variations","why":"30 variations of unparalleled invention"},{"composer":"Beethoven","work":"Diabelli Variations","why":"A waltz transformed into cosmos"},{"composer":"Brahms","work":"Variations on a Theme by Haydn","why":"Orchestral variation mastery"}]'::jsonb),
  ('tone-poem', 'Tone Poem / Symphonic Poem', 'Orchestral', 'Romantic/Modern', 'A single-movement orchestral work that tells a story, depicts a scene, or illustrates an idea.', '[{"aspect":"Form","description":"Free—shaped by the program (story)"},{"aspect":"Length","description":"Usually 10-25 minutes"},{"aspect":"Character","description":"Highly descriptive, colorful orchestration"}]'::jsonb, '{"How music 'paints' the programmatic story","Leitmotifs representing characters or ideas","The narrative arc through sound alone"}', '[{"composer":"Strauss","work":"Also sprach Zarathustra","why":"Philosophy in sound (famous sunrise opening)"},{"composer":"Smetana","work":"The Moldau","why":"A river''s journey through Czech landscape"},{"composer":"Debussy","work":"Prélude à l''après-midi d''un faune","why":"Impressionist dream of a mythological afternoon"}]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  period = EXCLUDED.period,
  description = EXCLUDED.description,
  structure = EXCLUDED.structure,
  listen_for = EXCLUDED.listen_for,
  key_works = EXCLUDED.key_works;
