-- Seed data for kickstart_lessons
-- Generated: 2025-12-11T08:34:02.715Z

INSERT INTO public.kickstart_lessons (day, title, subtitle, icon, duration, content, badge_id, is_active)
VALUES
  (1, 'Welcome to Classical Music', 'Your Journey Begins', 'music-note', '10 minutes', '{"introduction":"Classical music isn''t as complicated as you think. Today, we''ll prove it.","keyInsight":"Classical music is simply organized sound telling stories and expressing emotions—just like any other music. The only difference is the vocabulary.","mainLesson":{"title":"The Three Things You Need to Know","points":[{"title":"Melody","description":"The tune you can hum. Every piece has at least one memorable melody."},{"title":"Rhythm","description":"The pulse and pattern. Classical music has driving rhythms, gentle sways, and everything between."},{"title":"Structure","description":"How it''s organized. Most pieces repeat and develop ideas—listen for the return of familiar themes."}]},"listenToday":{"piece":"Beethoven: Symphony No. 5, First Movement","duration":"7 minutes","whyThisPiece":"The most famous four notes in music. You already know them. Now hear how Beethoven builds an entire movement from them.","whatToListenFor":["The ''short-short-short-LONG'' rhythm that appears everywhere","How tension builds and releases","The triumphant horn call in the middle"],"spotifySearch":"Beethoven Symphony 5 Kleiber","youtubeSearch":"Beethoven Symphony 5 First Movement"},"termOfTheDay":{"term":"Movement","definition":"A self-contained section of a larger work. Think of chapters in a book. A symphony usually has 4 movements."}}'::jsonb, 'first_listen', TRUE),
  (2, 'The Orchestra', 'A City of Sound', 'people', '12 minutes', '{"introduction":"An orchestra is like a city: different neighborhoods (sections), each with its own character, working together.","keyInsight":"Once you can identify instrument families, the orchestra stops being a blur of sound and becomes a conversation between distinct voices.","mainLesson":{"title":"The Four Families","points":[{"title":"Strings","description":"The foundation. Violins, violas, cellos, basses. They can sing, whisper, or roar. Make up about 60% of the orchestra."},{"title":"Woodwinds","description":"The colors. Flutes, oboes, clarinets, bassoons. Each has a distinct personality—listen for solo melodies passed between them."},{"title":"Brass","description":"The power. Trumpets, horns, trombones, tubas. Used for grandeur, nobility, and climaxes. A little goes a long way."},{"title":"Percussion","description":"The punctuation. Timpani, cymbals, triangle. They mark important moments and add drama or color."}]},"listenToday":{"piece":"Britten: The Young Person''s Guide to the Orchestra","duration":"17 minutes","whyThisPiece":"Britten literally introduces each instrument family with a theme that showcases their character. It''s classical music''s best self-guided tour.","whatToListenFor":["How each section has a distinct color","The personality of each instrument","The grand finale bringing everyone together"],"spotifySearch":"Britten Young Person''s Guide Orchestra","youtubeSearch":"Britten Young Person''s Guide to the Orchestra"},"termOfTheDay":{"term":"Orchestration","definition":"The art of choosing which instruments play which parts. Great orchestrators make the same notes sound completely different."}}'::jsonb, 'orchestra_explorer', TRUE),
  (3, 'The Eras', 'A Musical Time Machine', 'time', '15 minutes', '{"introduction":"Classical music spans 400+ years. Each era has a distinct sound—once you hear the differences, you can place almost any piece.","keyInsight":"Baroque = ornate and energetic. Classical = balanced and clear. Romantic = emotional and big. Modern = experimental and colorful.","mainLesson":{"title":"The Four Main Eras","points":[{"title":"Baroque (1600-1750)","description":"Ornamental, energetic, harpsichord-driven. Think Bach, Vivaldi, Handel. Sounds: constant motion, decoration, terraced dynamics."},{"title":"Classical (1750-1820)","description":"Elegant, balanced, clear. Think Haydn, Mozart, early Beethoven. Sounds: graceful phrases, wit, symmetry."},{"title":"Romantic (1820-1900)","description":"Emotional, personal, expansive. Think Chopin, Brahms, Tchaikovsky. Sounds: big orchestras, long melodies, drama."},{"title":"Modern (1900-today)","description":"Experimental, diverse, colorful. Think Debussy, Stravinsky, Glass. Sounds: new harmonies, rhythm experiments, surprise."}]},"listenToday":{"piece":"A Mini-Tour Through Time (3 short excerpts)","duration":"10 minutes total","whyThisPiece":"Hearing is believing. Three minutes from each era will train your ear instantly.","whatToListenFor":["Baroque: Bach''s Brandenburg Concerto No. 3 (constant motion, bright energy)","Romantic: Chopin''s Nocturne Op. 9 No. 2 (singing melody, emotional freedom)","Modern: Debussy''s Arabesque No. 1 (floating harmony, dreamy atmosphere)"],"spotifySearch":"Bach Brandenburg 3 / Chopin Nocturne Op 9 / Debussy Arabesque","youtubeSearch":"Bach Brandenburg 3 first movement"},"termOfTheDay":{"term":"Period","definition":"A span of time in music history with shared stylistic features. Also called an ''era.'' Knowing periods helps you set expectations before listening."}}'::jsonb, 'time_traveler', TRUE),
  (4, 'Form and Structure', 'The Hidden Blueprint', 'grid', '12 minutes', '{"introduction":"Every building has an architecture. So does every piece of music. Understanding form turns chaos into story.","keyInsight":"The most important form is ''Sonata Form'': introduce themes (A & B), develop them, then bring them back changed. It''s the foundation of symphonies and concertos.","mainLesson":{"title":"The Essential Forms","points":[{"title":"Binary (AB)","description":"Two parts. Simple songs often use this: verse-chorus-repeat."},{"title":"Ternary (ABA)","description":"Three parts where the third brings back the first. Like a sandwich—the return is satisfying."},{"title":"Sonata Form","description":"Exposition (meet the themes) → Development (themes get transformed) → Recapitulation (themes return home). The big one."},{"title":"Rondo (ABACA...)","description":"A main theme keeps returning between contrasting episodes. Great for upbeat finales."}]},"listenToday":{"piece":"Mozart: Symphony No. 40, First Movement","duration":"8 minutes","whyThisPiece":"Perfect sonata form in action. The famous opening theme, the contrasting second theme, the development, and the triumphant return—all clearly audible.","whatToListenFor":["0:00 - First theme (agitated, minor key, famous melody)","1:00 - Second theme (gentler, related major key)","2:30 - Development (themes fragmented, keys wander)","5:00 - Recapitulation (first theme returns, now we''re home)"],"spotifySearch":"Mozart Symphony 40 First Movement","youtubeSearch":"Mozart Symphony 40 K550 First Movement"},"termOfTheDay":{"term":"Sonata Form","definition":"The most important structure in classical music. Three sections: Exposition (themes introduced), Development (themes explored), Recapitulation (themes return)."}}'::jsonb, 'form_finder', TRUE),
  (5, 'Your Personal Path', 'Where to Go From Here', 'compass', '10 minutes', '{"introduction":"You now have the tools. The question is: what speaks to you?","keyInsight":"There''s no ''right'' way to explore classical music. Follow your curiosity. If you love a piece, find more by that composer. If you love an era, explore its stars.","mainLesson":{"title":"Five Paths Forward","points":[{"title":"The Emotional Path","description":"Start with how music makes you feel. Love drama? Try Beethoven, Brahms. Love calm? Try Bach, Debussy."},{"title":"The Era Path","description":"Pick an era that resonates and go deep. Listen to its major composers, understand its context."},{"title":"The Composer Path","description":"Find a composer you love and explore their full output. Hear how they evolved over their life."},{"title":"The Form Path","description":"Love symphonies? Listen to the great ones chronologically. Love piano? Explore the solo repertoire."},{"title":"The Challenge Path","description":"Set goals: all Beethoven symphonies, one new composer per month, a piece you initially found ''difficult.''"}]},"listenToday":{"piece":"Your Choice from the Weekly Album","duration":"Variable","whyThisPiece":"Check this week''s Album Pick and start your journey. Return to the app each week for new discoveries.","whatToListenFor":["Whatever catches your ear","Moments that move you","Questions that arise (look them up in the Glossary!)"],"spotifySearch":"See Weekly Album Pick","youtubeSearch":"See Weekly Album Pick"},"termOfTheDay":{"term":"Repertoire","definition":"The collection of works a performer plays, or the body of works in a genre. Building your personal repertoire of pieces you know and love is the lifelong joy of classical music."}}'::jsonb, 'journey_begun', TRUE)
ON CONFLICT (day) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  icon = EXCLUDED.icon,
  duration = EXCLUDED.duration,
  content = EXCLUDED.content,
  badge_id = EXCLUDED.badge_id,
  is_active = EXCLUDED.is_active;
