-- Seed data for weekly_albums
-- Generated: 2025-12-11T08:34:02.714Z

INSERT INTO public.weekly_albums (week, title, artist, year, description, why_listen, spotify_uri, apple_music_url, key_moments, listener_level)
VALUES
  (1, 'Beethoven: Symphony No. 5', 'Carlos Kleiber / Vienna Philharmonic', 1974, 'The legendary recording that defines this symphony. Kleiber''s electric intensity brings out every detail of Beethoven''s vision—from the famous four-note motif to the triumphant finale.', 'This is THE recording to understand why Beethoven 5 matters. Kleiber''s tempo choices and dynamic control are revelatory.', 'spotify:album:1234', 'https://music.apple.com', '[{"time":"0:00","description":"The famous fate motif—four notes that drive everything"},{"time":"7:23","description":"Second movement''s peaceful contrast"},{"time":"21:45","description":"The bridge from darkness to the triumphant finale"}]'::jsonb, NULL),
  (2, 'Bach: Goldberg Variations', 'Glenn Gould (1981 Recording)', 1981, 'Gould''s final studio recording—slower, more profound than his famous 1955 debut. Thirty variations of infinite beauty and intellectual depth.', 'Experience Bach''s architecture through a master pianist''s mature vision. The 1981 version has depth that reveals itself over many listens.', 'spotify:album:5678', 'https://music.apple.com', '[{"time":"0:00","description":"The Aria—the theme from which all grows"},{"time":"25:00","description":"Variation 15—a profound, introspective canon"},{"time":"51:00","description":"The Quodlibet—Bach''s musical joke"}]'::jsonb, NULL),
  (3, 'Debussy: Orchestral Works', 'Claudio Abbado / London Symphony', 1999, 'La Mer, Prélude à l''après-midi d''un faune, and Nocturnes in luminous performances. The colors of Impressionism captured perfectly.', 'If you think classical music is heavy and formal, this will change your mind. Debussy is pure color and atmosphere.', 'spotify:album:9012', 'https://music.apple.com', '[{"time":"0:00","description":"La Mer opens with the sea at dawn"},{"time":"23:00","description":"Prélude—the famous flute melody evoking a faun''s dream"}]'::jsonb, NULL),
  (4, 'Chopin: Nocturnes', 'Maurizio Pollini', 2005, 'All 21 Nocturnes performed with aristocratic poise and deep feeling. The perfect introduction to Romantic piano music.', 'Chopin invented the piano nocturne. These pieces are the soul of Romantic pianism—beauty without excess.', 'spotify:album:3456', 'https://music.apple.com', '[{"time":"6:30","description":"Op. 9 No. 2—the most famous nocturne"},{"time":"45:00","description":"Op. 48 No. 1—a nocturne with dramatic depth"}]'::jsonb, NULL),
  (5, 'Mozart: Requiem', 'John Eliot Gardiner / English Baroque Soloists', 1986, 'Mozart''s unfinished masterpiece in a lean, dramatic performance on period instruments. The Dies Irae is terrifying; the Lacrimosa is heartbreaking.', 'Mozart died writing this work. The combination of mortality and divine beauty makes it uniquely powerful.', 'spotify:album:7890', 'https://music.apple.com', '[{"time":"0:00","description":"Introit—immediate, somber beauty"},{"time":"5:30","description":"Dies Irae—the Day of Wrath explodes"},{"time":"35:00","description":"Lacrimosa—where Mozart''s pen stopped"}]'::jsonb, NULL),
  (6, 'Vivaldi: The Four Seasons', 'Europa Galante / Fabio Biondi', 1991, 'A historically-informed performance that strips away centuries of heavy interpretation. The result is vivid, immediate, and exciting.', 'You''ve heard Four Seasons in every coffee shop—but not like this. Period instruments reveal Vivaldi''s original colors.', 'spotify:album:1111', 'https://music.apple.com', '[{"time":"0:00","description":"Spring—birds, brooks, and storms"},{"time":"20:00","description":"Summer''s violent thunderstorm"},{"time":"32:00","description":"Winter''s icy chill and warmth by the fire"}]'::jsonb, 'beginner'),
  (7, 'Brahms: Symphony No. 4', 'Carlos Kleiber / Vienna Philharmonic', 1980, 'Another Kleiber miracle. The fourth symphony''s autumnal melancholy and final passacaglia are rendered with perfect balance of structure and emotion.', 'Brahms'' final symphony is a meditation on endings. The last movement''s variations are among the greatest pages in all music.', 'spotify:album:2222', 'https://music.apple.com', '[{"time":"0:00","description":"The sighing opening melody"},{"time":"29:00","description":"Fourth movement passacaglia begins"}]'::jsonb, NULL),
  (8, 'Stravinsky: The Rite of Spring', 'Pierre Boulez / Cleveland Orchestra', 1991, 'The work that changed music forever, in a performance of crystalline clarity. Every explosive rhythm and strange harmony is perfectly balanced.', 'This caused a riot at its 1913 premiere. A century later, it still sounds revolutionary.', 'spotify:album:3333', 'https://music.apple.com', '[{"time":"0:00","description":"The mysterious bassoon solo"},{"time":"3:30","description":"The Augurs of Spring—pounding, dissonant chords"},{"time":"28:00","description":"Sacrificial Dance—primal rhythmic violence"}]'::jsonb, 'advanced'),
  (9, 'Tchaikovsky: Swan Lake Suite', 'Herbert von Karajan / Vienna Philharmonic', 1965, 'The essence of the beloved ballet in orchestral highlights. The famous theme, the dance of the cygnets, and the tragic finale.', 'Pure Romantic melody and orchestral color. Tchaikovsky''s gift for tune-writing is on full display.', 'spotify:album:4444', 'https://music.apple.com', '[{"time":"0:00","description":"The iconic swan theme on oboe"},{"time":"8:00","description":"Dance of the Little Swans—delightful precision"}]'::jsonb, NULL),
  (10, 'Handel: Messiah (Highlights)', 'Trevor Pinnock / The English Concert', 1988, 'Period-instrument performance bringing freshness to the beloved oratorio. The Hallelujah Chorus as you''ve never heard it.', 'This isn''t just Christmas music. Handel''s drama and melody speak to everyone.', 'spotify:album:5555', 'https://music.apple.com', '[{"time":"0:00","description":"Every Valley—the opening tenor aria"},{"time":"24:00","description":"The Hallelujah Chorus"}]'::jsonb, NULL),
  (11, 'Ravel: Piano Concerto in G', 'Krystian Zimerman / Pierre Boulez / Cleveland Orchestra', 1994, 'Jazz-inflected brilliance meets French elegance. The slow movement is one of the most beautiful things Ravel ever wrote.', 'Proof that 20th-century classical music can be immediately appealing. The slow movement will haunt you.', 'spotify:album:6666', 'https://music.apple.com', '[{"time":"0:00","description":"The whip crack that opens the work"},{"time":"8:30","description":"Second movement—simple, profound beauty"},{"time":"18:00","description":"Finale—jazzy virtuosity"}]'::jsonb, NULL),
  (12, 'Dvorak: Symphony No. 9 ''From the New World''', 'Rafael Kubelík / Bavarian Radio Symphony', 1970, 'A Czech composer''s love letter to America, performed by a Czech émigré conductor. The famous Largo is unforgettable.', 'One of the most approachable symphonies ever written. The melodies feel like folk songs you already know.', 'spotify:album:7777', 'https://music.apple.com', '[{"time":"0:00","description":"Introduction building to the main theme"},{"time":"11:00","description":"The Largo—''Going Home'' melody on English horn"},{"time":"35:00","description":"Finale—all themes return in triumph"}]'::jsonb, NULL)
ON CONFLICT (week) DO UPDATE SET
  title = EXCLUDED.title,
  artist = EXCLUDED.artist,
  year = EXCLUDED.year,
  description = EXCLUDED.description,
  why_listen = EXCLUDED.why_listen,
  spotify_uri = EXCLUDED.spotify_uri,
  apple_music_url = EXCLUDED.apple_music_url,
  key_moments = EXCLUDED.key_moments,
  listener_level = EXCLUDED.listener_level;
