-- Seed data for terms
-- Generated: 2025-12-11T08:34:02.713Z

INSERT INTO public.terms (id, term, category, short_definition, long_definition, media_links)
VALUES
  (1, 'Adagio', 'Tempo', 'A slow, expressive tempo marking.', 'A slow tempo, slower than andante but faster than largo. Often used for expressive, lyrical movements.', '[{"label":"Hear Adagio tempos","url":"https://www.youtube.com/results?search_query=adagio+classical","type":"youtube"}]'::jsonb),
  (2, 'Allegro', 'Tempo', 'A fast, lively tempo marking.', 'A fast, lively tempo. One of the most common tempo markings in classical music.', '[{"label":"Allegro examples","url":"https://www.youtube.com/results?search_query=allegro+tempo+classical","type":"youtube"}]'::jsonb),
  (3, 'Andante', 'Tempo', 'Moderate, walking pace tempo.', 'A moderate, walking pace tempo. Neither fast nor slow.', '[{"label":"Walk at Andante","url":"https://www.youtube.com/results?search_query=andante+tempo+classical","type":"youtube"}]'::jsonb),
  (4, 'Aria', 'Form', 'A self-contained piece for solo voice, typically in an opera or oratorio, with instrumental accompaniment.', 'A self-contained piece for solo voice, typically in an opera or oratorio, with instrumental accompaniment.', '{}'),
  (5, 'Arpeggio', 'Technique', 'Playing the notes of a chord in succession rather than simultaneously, like a harp.', 'Playing the notes of a chord in succession rather than simultaneously, like a harp.', '{}'),
  (6, 'Atonality', 'Harmony', 'Music without a tonal center or key. Associated with Schoenberg and the Second Viennese School.', 'Music without a tonal center or key. Associated with Schoenberg and the Second Viennese School.', '{}'),
  (7, 'Cadence', 'Harmony', 'A harmonic progression that creates a sense of resolution or pause, like punctuation in music.', 'A harmonic progression that creates a sense of resolution or pause, like punctuation in music.', '{}'),
  (8, 'Cadenza', 'Form', 'A virtuosic solo passage, often improvised, near the end of a concerto movement.', 'A virtuosic solo passage, often improvised, near the end of a concerto movement.', '{}'),
  (9, 'Canon', 'Form', 'A compositional technique where a melody is imitated exactly by one or more voices at fixed intervals.', 'A compositional technique where a melody is imitated exactly by one or more voices at fixed intervals.', '{}'),
  (10, 'Cantata', 'Form', 'A vocal composition with instrumental accompaniment, typically for church services.', 'A vocal composition with instrumental accompaniment, typically for church services.', '{}'),
  (11, 'Chamber Music', 'Genre', 'Music for small ensembles (2-9 players), with one player per part, designed for intimate settings.', 'Music for small ensembles (2-9 players), with one player per part, designed for intimate settings.', '{}'),
  (12, 'Chord', 'Harmony', 'Three or more notes sounded simultaneously, forming the basis of harmony.', 'Three or more notes sounded simultaneously, forming the basis of harmony.', '{}'),
  (13, 'Chromaticism', 'Harmony', 'Use of notes outside the main key, adding color and tension to the harmony.', 'Use of notes outside the main key, adding color and tension to the harmony.', '{}'),
  (14, 'Coda', 'Form', 'A concluding passage that brings a piece or movement to an end, often after the main structure.', 'A concluding passage that brings a piece or movement to an end, often after the main structure.', '{}'),
  (15, 'Concerto', 'Form', 'A work for solo instrument(s) with orchestral accompaniment, typically in three movements.', 'A work for solo instrument(s) with orchestral accompaniment, typically in three movements.', '{}'),
  (16, 'Consonance', 'Harmony', 'Pleasing, stable combinations of notes that sound harmonious together.', 'Pleasing, stable combinations of notes that sound harmonious together.', '{}'),
  (17, 'Counterpoint', 'Technique', 'The art of combining two or more independent melodic lines simultaneously.', 'The art of combining two or more independent melodic lines simultaneously.', '{}'),
  (18, 'Crescendo', 'Dynamics', 'A gradual increase in volume, building intensity over a passage.', 'A gradual increase in volume, building intensity over a passage.', '{}'),
  (19, 'Development', 'Form', 'The middle section of sonata form where themes are transformed, fragmented, and explored.', 'The middle section of sonata form where themes are transformed, fragmented, and explored.', '{}'),
  (20, 'Diminuendo', 'Dynamics', 'A gradual decrease in volume, softening the sound.', 'A gradual decrease in volume, softening the sound.', '{}'),
  (21, 'Dissonance', 'Harmony', 'Unstable, tension-creating combinations of notes that seek resolution.', 'Unstable, tension-creating combinations of notes that seek resolution.', '{}'),
  (22, 'Dynamics', 'Expression', 'The variation in loudness of music, from pianissimo (very soft) to fortissimo (very loud).', 'The variation in loudness of music, from pianissimo (very soft) to fortissimo (very loud).', '{}'),
  (23, 'Étude', 'Form', 'A study piece designed to develop technique, but often also a concert work.', 'A study piece designed to develop technique, but often also a concert work.', '{}'),
  (24, 'Exposition', 'Form', 'The opening section of sonata form where main themes are presented.', 'The opening section of sonata form where main themes are presented.', '{}'),
  (25, 'Fermata', 'Notation', 'A symbol indicating a note should be held longer than its written value, at performer''s discretion.', 'A symbol indicating a note should be held longer than its written value, at performer''s discretion.', '{}'),
  (26, 'Forte', 'Dynamics', 'Loud. Marked as ''f'' in the score.', 'Loud. Marked as ''f'' in the score.', '{}'),
  (27, 'Fugue', 'Form', 'A complex contrapuntal form where a theme (subject) is introduced and developed through multiple voices.', 'A complex contrapuntal form where a theme (subject) is introduced and developed through multiple voices.', '{}'),
  (28, 'Harmony', 'Theory', 'The simultaneous combination of notes to produce chords and chord progressions.', 'The simultaneous combination of notes to produce chords and chord progressions.', '{}'),
  (29, 'Homophony', 'Texture', 'A texture where one melody is accompanied by chords, typical of Classical music.', 'A texture where one melody is accompanied by chords, typical of Classical music.', '{}'),
  (30, 'Interval', 'Theory', 'The distance between two pitches, measured in scale steps.', 'The distance between two pitches, measured in scale steps.', '{}'),
  (31, 'Key', 'Theory', 'The tonal center of a piece, determining which notes sound ''home'' and which create tension.', 'The tonal center of a piece, determining which notes sound ''home'' and which create tension.', '{}'),
  (32, 'Largo', 'Tempo', 'A very slow, broad tempo. One of the slowest tempo markings.', 'A very slow, broad tempo. One of the slowest tempo markings.', '{}'),
  (33, 'Legato', 'Technique', 'Smooth, connected playing without breaks between notes.', 'Smooth, connected playing without breaks between notes.', '{}'),
  (34, 'Leitmotif', 'Technique', 'A recurring musical theme associated with a person, place, idea, or emotion.', 'A recurring musical theme associated with a person, place, idea, or emotion.', '{}'),
  (35, 'Libretto', 'Opera', 'The text of an opera, oratorio, or musical, setting the story and words to be sung.', 'The text of an opera, oratorio, or musical, setting the story and words to be sung.', '{}'),
  (36, 'Mazurka', 'Form', 'A Polish folk dance in triple meter with accent on the second or third beat.', 'A Polish folk dance in triple meter with accent on the second or third beat.', '{}'),
  (37, 'Melody', 'Theory', 'A sequence of notes perceived as a single, coherent musical line.', 'A sequence of notes perceived as a single, coherent musical line.', '{}'),
  (38, 'Meter', 'Rhythm', 'The pattern of strong and weak beats organizing music in time.', 'The pattern of strong and weak beats organizing music in time.', '{}'),
  (39, 'Minuet', 'Form', 'A stately dance in triple meter, often the third movement of Classical symphonies.', 'A stately dance in triple meter, often the third movement of Classical symphonies.', '{}'),
  (40, 'Modulation', 'Harmony', 'Changing from one key to another within a piece.', 'Changing from one key to another within a piece.', '{}'),
  (41, 'Motif', 'Theory', 'A short, distinctive musical idea that recurs and develops throughout a piece.', 'A short, distinctive musical idea that recurs and develops throughout a piece.', '{}'),
  (42, 'Movement', 'Form', 'A self-contained section of a larger work, with its own tempo and character.', 'A self-contained section of a larger work, with its own tempo and character.', '{}'),
  (43, 'Nocturne', 'Form', 'A dreamy, lyrical piano piece evoking night, pioneered by John Field and perfected by Chopin.', 'A dreamy, lyrical piano piece evoking night, pioneered by John Field and perfected by Chopin.', '{}'),
  (44, 'Octave', 'Theory', 'The interval between two notes where one has double the frequency of the other.', 'The interval between two notes where one has double the frequency of the other.', '{}'),
  (45, 'Opera', 'Genre', 'A dramatic work combining singing, orchestral music, and usually theatrical staging.', 'A dramatic work combining singing, orchestral music, and usually theatrical staging.', '{}'),
  (46, 'Opus', 'Notation', 'Latin for ''work.'' A number assigned to a composer''s pieces for cataloging.', 'Latin for ''work.'' A number assigned to a composer''s pieces for cataloging.', '{}'),
  (47, 'Oratorio', 'Genre', 'A large-scale work for orchestra, choir, and soloists, usually on a religious subject, performed without staging.', 'A large-scale work for orchestra, choir, and soloists, usually on a religious subject, performed without staging.', '{}'),
  (48, 'Orchestra', 'Ensemble', 'A large instrumental ensemble with strings, winds, brass, and percussion sections.', 'A large instrumental ensemble with strings, winds, brass, and percussion sections.', '{}'),
  (49, 'Orchestration', 'Technique', 'The art of assigning musical lines to different instruments for timbral effect.', 'The art of assigning musical lines to different instruments for timbral effect.', '{}'),
  (50, 'Ostinato', 'Technique', 'A short musical pattern repeated persistently throughout a piece or section.', 'A short musical pattern repeated persistently throughout a piece or section.', '{}'),
  (51, 'Overture', 'Form', 'An orchestral introduction to an opera, oratorio, or suite.', 'An orchestral introduction to an opera, oratorio, or suite.', '{}'),
  (52, 'Pedal', 'Technique', 'A sustained bass note held while harmonies change above it.', 'A sustained bass note held while harmonies change above it.', '{}'),
  (53, 'Phrase', 'Form', 'A musical sentence—a coherent group of notes forming a distinct musical thought.', 'A musical sentence—a coherent group of notes forming a distinct musical thought.', '{}'),
  (54, 'Pianissimo', 'Dynamics', 'Very soft. Marked as ''pp'' in the score.', 'Very soft. Marked as ''pp'' in the score.', '{}'),
  (55, 'Piano', 'Dynamics', 'Soft. Marked as ''p'' in the score. (Also the instrument name)', 'Soft. Marked as ''p'' in the score. (Also the instrument name)', '{}'),
  (56, 'Pitch', 'Theory', 'The perceived highness or lowness of a sound, determined by frequency.', 'The perceived highness or lowness of a sound, determined by frequency.', '{}'),
  (57, 'Pizzicato', 'Technique', 'Plucking string instruments instead of bowing them.', 'Plucking string instruments instead of bowing them.', '{}'),
  (58, 'Polyphony', 'Texture', 'A texture featuring multiple independent melodic lines sounding simultaneously.', 'A texture featuring multiple independent melodic lines sounding simultaneously.', '{}'),
  (59, 'Prelude', 'Form', 'An introductory piece, or a short standalone composition, especially for piano.', 'An introductory piece, or a short standalone composition, especially for piano.', '{}'),
  (60, 'Presto', 'Tempo', 'A very fast tempo, faster than allegro.', 'A very fast tempo, faster than allegro.', '{}'),
  (61, 'Program Music', 'Genre', 'Instrumental music that tells a story or depicts scenes, in contrast to ''absolute'' music.', 'Instrumental music that tells a story or depicts scenes, in contrast to ''absolute'' music.', '{}'),
  (62, 'Recapitulation', 'Form', 'The return of the main themes in sonata form, typically in the home key.', 'The return of the main themes in sonata form, typically in the home key.', '{}'),
  (63, 'Recitative', 'Opera', 'Speech-like singing in opera that advances the plot between arias.', 'Speech-like singing in opera that advances the plot between arias.', '{}'),
  (64, 'Requiem', 'Form', 'A Mass for the dead, setting the Latin Requiem text to music.', 'A Mass for the dead, setting the Latin Requiem text to music.', '{}'),
  (65, 'Rest', 'Notation', 'A symbol indicating silence for a specific duration.', 'A symbol indicating silence for a specific duration.', '{}'),
  (66, 'Rhapsody', 'Form', 'A free-form, often virtuosic piece with an improvisatory, episodic character.', 'A free-form, often virtuosic piece with an improvisatory, episodic character.', '{}'),
  (67, 'Rhythm', 'Theory', 'The pattern of durations and accents in music over time.', 'The pattern of durations and accents in music over time.', '{}'),
  (68, 'Ritardando', 'Tempo', 'Gradually slowing down the tempo.', 'Gradually slowing down the tempo.', '{}'),
  (69, 'Rondo', 'Form', 'A form with a recurring main theme alternating with contrasting episodes (ABACA).', 'A form with a recurring main theme alternating with contrasting episodes (ABACA).', '{}'),
  (70, 'Rubato', 'Expression', 'Flexible tempo, ''stealing'' time by speeding up or slowing down for expression.', 'Flexible tempo, ''stealing'' time by speeding up or slowing down for expression.', '{}'),
  (71, 'Scale', 'Theory', 'A sequence of notes arranged in ascending or descending order by pitch.', 'A sequence of notes arranged in ascending or descending order by pitch.', '{}'),
  (72, 'Scherzo', 'Form', 'A lively, often humorous movement that replaced the minuet in Romantic works.', 'A lively, often humorous movement that replaced the minuet in Romantic works.', '{}'),
  (73, 'Score', 'Notation', 'The written form of a musical composition showing all parts together.', 'The written form of a musical composition showing all parts together.', '{}'),
  (74, 'Sforzando', 'Dynamics', 'A sudden, strong accent on a single note or chord. Marked ''sfz''.', 'A sudden, strong accent on a single note or chord. Marked ''sfz''.', '{}'),
  (75, 'Sonata', 'Form', 'A multi-movement work for solo instrument or piano with another instrument.', 'A multi-movement work for solo instrument or piano with another instrument.', '{}'),
  (76, 'Sonata Form', 'Form', 'A structure with exposition, development, and recapitulation sections—the foundation of Classical music.', 'A structure with exposition, development, and recapitulation sections—the foundation of Classical music.', '{}'),
  (77, 'Soprano', 'Voice', 'The highest singing voice type, or the highest part in a choral work.', 'The highest singing voice type, or the highest part in a choral work.', '{}'),
  (78, 'Staccato', 'Technique', 'Short, detached notes with silence between them.', 'Short, detached notes with silence between them.', '{}'),
  (79, 'Staff', 'Notation', 'The five horizontal lines on which music notes are written.', 'The five horizontal lines on which music notes are written.', '{}'),
  (80, 'String Quartet', 'Ensemble', 'An ensemble of two violins, viola, and cello, or music written for this group.', 'An ensemble of two violins, viola, and cello, or music written for this group.', '{}'),
  (81, 'Suite', 'Form', 'A collection of dance movements or pieces grouped together.', 'A collection of dance movements or pieces grouped together.', '{}'),
  (82, 'Symphony', 'Form', 'A large-scale orchestral work, typically in four movements.', 'A large-scale orchestral work, typically in four movements.', '{}'),
  (83, 'Syncopation', 'Rhythm', 'Accenting beats that are normally weak, creating rhythmic interest.', 'Accenting beats that are normally weak, creating rhythmic interest.', '{}'),
  (84, 'Tempo', 'Theory', 'The speed at which a piece of music is performed.', 'The speed at which a piece of music is performed.', '{}'),
  (85, 'Tenor', 'Voice', 'A high male singing voice, between bass and countertenor.', 'A high male singing voice, between bass and countertenor.', '{}'),
  (86, 'Theme', 'Theory', 'A main melodic idea that forms the basis of a musical work.', 'A main melodic idea that forms the basis of a musical work.', '{}'),
  (87, 'Theme and Variations', 'Form', 'A form presenting a theme followed by modified versions of it.', 'A form presenting a theme followed by modified versions of it.', '{}'),
  (88, 'Timbre', 'Theory', 'The unique quality or ''color'' of a sound that distinguishes instruments.', 'The unique quality or ''color'' of a sound that distinguishes instruments.', '{}'),
  (89, 'Time Signature', 'Notation', 'Numbers at the start of music indicating beats per measure and note value of each beat.', 'Numbers at the start of music indicating beats per measure and note value of each beat.', '{}'),
  (90, 'Toccata', 'Form', 'A virtuosic showpiece, often for keyboard, featuring rapid passage work.', 'A virtuosic showpiece, often for keyboard, featuring rapid passage work.', '{}'),
  (91, 'Tonality', 'Theory', 'The system of organizing music around a central pitch or ''key.''', 'The system of organizing music around a central pitch or ''key.''', '{}'),
  (92, 'Tone Poem', 'Form', 'A single-movement orchestral work depicting a story, scene, or idea. Also called symphonic poem.', 'A single-movement orchestral work depicting a story, scene, or idea. Also called symphonic poem.', '{}'),
  (93, 'Transpose', 'Technique', 'Moving a piece of music to a different key while keeping the same intervals.', 'Moving a piece of music to a different key while keeping the same intervals.', '{}'),
  (94, 'Tremolo', 'Technique', 'Rapid repetition of a single note or alternation between two notes.', 'Rapid repetition of a single note or alternation between two notes.', '{}'),
  (95, 'Trill', 'Technique', 'Rapid alternation between a note and the note above it as ornamentation.', 'Rapid alternation between a note and the note above it as ornamentation.', '{}'),
  (96, 'Trio', 'Form', 'A composition for three performers, or the middle section of a minuet/scherzo.', 'A composition for three performers, or the middle section of a minuet/scherzo.', '{}'),
  (97, 'Twelve-Tone', 'Technique', 'A method of composition using all 12 chromatic notes equally, developed by Schoenberg.', 'A method of composition using all 12 chromatic notes equally, developed by Schoenberg.', '{}'),
  (98, 'Unison', 'Texture', 'All voices or instruments playing the same notes at the same pitch.', 'All voices or instruments playing the same notes at the same pitch.', '{}'),
  (99, 'Vibrato', 'Technique', 'A slight, rapid variation in pitch to add warmth and expression.', 'A slight, rapid variation in pitch to add warmth and expression.', '{}'),
  (100, 'Virtuoso', 'Performance', 'A musician with exceptional technical skill and artistry.', 'A musician with exceptional technical skill and artistry.', '{}'),
  (101, 'Waltz', 'Form', 'A dance in triple meter (3/4) with emphasis on the first beat.', 'A dance in triple meter (3/4) with emphasis on the first beat.', '{}'),
  (102, 'Whole Tone Scale', 'Theory', 'A scale with only whole steps, creating a dreamlike, ambiguous quality.', 'A scale with only whole steps, creating a dreamlike, ambiguous quality.', '{}'),
  (103, 'Basso Continuo', 'Baroque', 'A continuous bass line in Baroque music, typically played by cello and harpsichord.', 'A continuous bass line in Baroque music, typically played by cello and harpsichord.', '{}'),
  (104, 'Da Capo', 'Notation', 'An instruction to return to the beginning of the piece.', 'An instruction to return to the beginning of the piece.', '{}'),
  (105, 'Fortissimo', 'Dynamics', 'Very loud. Marked as ''ff'' in the score.', 'Very loud. Marked as ''ff'' in the score.', '{}'),
  (106, 'Glissando', 'Technique', 'A slide from one pitch to another, often on piano or harp.', 'A slide from one pitch to another, often on piano or harp.', '{}'),
  (107, 'Impressionism', 'Style', 'A style emphasizing atmosphere and color over form, pioneered by Debussy.', 'A style emphasizing atmosphere and color over form, pioneered by Debussy.', '{}'),
  (108, 'Intermezzo', 'Form', 'A short piece between larger sections, or a standalone lyrical piano piece.', 'A short piece between larger sections, or a standalone lyrical piano piece.', '{}'),
  (109, 'Major', 'Theory', 'A mode/key characterized by a bright, happy quality due to its interval pattern.', 'A mode/key characterized by a bright, happy quality due to its interval pattern.', '{}'),
  (110, 'Minor', 'Theory', 'A mode/key characterized by a darker, sadder quality due to its interval pattern.', 'A mode/key characterized by a darker, sadder quality due to its interval pattern.', '{}'),
  (111, 'Minimalism', 'Style', 'A style using repetition, slow change, and simple harmonies.', 'A style using repetition, slow change, and simple harmonies.', '{}'),
  (112, 'Motive', 'Theory', 'The smallest identifiable musical idea (same as motif).', 'The smallest identifiable musical idea (same as motif).', '{}'),
  (113, 'Opus Posthumous', 'Notation', 'A work published after the composer''s death.', 'A work published after the composer''s death.', '{}'),
  (114, 'Polonaise', 'Form', 'A stately Polish dance in triple meter with a distinctive rhythmic pattern.', 'A stately Polish dance in triple meter with a distinctive rhythmic pattern.', '{}'),
  (115, 'Recital', 'Performance', 'A concert by a solo performer or small ensemble, as invented by Liszt.', 'A concert by a solo performer or small ensemble, as invented by Liszt.', '{}'),
  (116, 'Romanticism', 'Style', 'The artistic movement (c.1820-1900) emphasizing emotion, individualism, and nature.', 'The artistic movement (c.1820-1900) emphasizing emotion, individualism, and nature.', '{}'),
  (117, 'Serenade', 'Form', 'Originally evening music for a beloved; later a multi-movement light orchestral work.', 'Originally evening music for a beloved; later a multi-movement light orchestral work.', '{}'),
  (118, 'Siciliano', 'Form', 'A slow dance in 6/8 or 12/8 meter with a lilting, pastoral character.', 'A slow dance in 6/8 or 12/8 meter with a lilting, pastoral character.', '{}'),
  (119, 'Symphonic Poem', 'Form', 'Same as tone poem—a programmatic orchestral work in one movement.', 'Same as tone poem—a programmatic orchestral work in one movement.', '{}'),
  (120, 'Tessitura', 'Voice', 'The comfortable range where a voice or instrument sounds best.', 'The comfortable range where a voice or instrument sounds best.', '{}'),
  (121, 'Texture', 'Theory', 'The way melodic, rhythmic, and harmonic materials combine—monophony, homophony, polyphony.', 'The way melodic, rhythmic, and harmonic materials combine—monophony, homophony, polyphony.', '{}'),
  (122, 'Tutti', 'Performance', 'All performers playing together, as opposed to a solo passage.', 'All performers playing together, as opposed to a solo passage.', '{}'),
  (123, 'Variations', 'Form', 'Altered versions of a theme, changing melody, harmony, rhythm, or character.', 'Altered versions of a theme, changing melody, harmony, rhythm, or character.', '{}'),
  (124, 'Vivace', 'Tempo', 'A lively, brisk tempo, similar to allegro but often with more energy.', 'A lively, brisk tempo, similar to allegro but often with more energy.', '{}'),
  (125, 'Absolute Music', 'Genre', 'Instrumental music without explicit narrative or pictorial content.', 'Instrumental music without explicit narrative or pictorial content.', '{}'),
  (126, 'Atonal', 'Harmony', 'Music without a key center, avoiding traditional tonal relationships.', 'Music without a key center, avoiding traditional tonal relationships.', '{}'),
  (127, 'Baritone', 'Voice', 'A male voice range between bass and tenor.', 'A male voice range between bass and tenor.', '{}'),
  (128, 'Baroque', 'Period', 'The musical era from roughly 1600-1750, characterized by ornate complexity.', 'The musical era from roughly 1600-1750, characterized by ornate complexity.', '{}'),
  (129, 'Bel Canto', 'Opera', 'Italian ''beautiful singing''—a vocal style emphasizing beauty of tone and agility.', 'Italian ''beautiful singing''—a vocal style emphasizing beauty of tone and agility.', '{}'),
  (130, 'Classical Period', 'Period', 'The musical era from roughly 1750-1820, emphasizing clarity and balance.', 'The musical era from roughly 1750-1820, emphasizing clarity and balance.', '{}'),
  (131, 'Clavichord', 'Instrument', 'A soft-toned keyboard instrument where strings are struck by tangents.', 'A soft-toned keyboard instrument where strings are struck by tangents.', '{}'),
  (132, 'Coloratura', 'Voice', 'Elaborate vocal ornamentation requiring great agility.', 'Elaborate vocal ornamentation requiring great agility.', '{}'),
  (133, 'Contralto', 'Voice', 'The lowest female voice type.', 'The lowest female voice type.', '{}'),
  (134, 'Countertenor', 'Voice', 'A male voice singing in falsetto, in the alto or soprano range.', 'A male voice singing in falsetto, in the alto or soprano range.', '{}'),
  (135, 'Double Stop', 'Technique', 'Playing two strings simultaneously on a bowed string instrument.', 'Playing two strings simultaneously on a bowed string instrument.', '{}'),
  (136, 'Expressionism', 'Style', 'An early 20th-century style expressing intense, often disturbing emotions.', 'An early 20th-century style expressing intense, often disturbing emotions.', '{}'),
  (137, 'Figured Bass', 'Baroque', 'A Baroque notation system indicating harmonies with numbers below the bass.', 'A Baroque notation system indicating harmonies with numbers below the bass.', '{}'),
  (138, 'Harpsichord', 'Instrument', 'A keyboard instrument where strings are plucked, not struck. Central to Baroque.', 'A keyboard instrument where strings are plucked, not struck. Central to Baroque.', '{}'),
  (139, 'Instrumentation', 'Technique', 'The specific combination of instruments used in a composition.', 'The specific combination of instruments used in a composition.', '{}'),
  (140, 'Lied', 'Form', 'German art song for voice and piano, setting poetry to music.', 'German art song for voice and piano, setting poetry to music.', '{}'),
  (141, 'Mass', 'Form', 'A musical setting of the Roman Catholic Mass texts.', 'A musical setting of the Roman Catholic Mass texts.', '{}'),
  (142, 'Mezzo-Soprano', 'Voice', 'A female voice between soprano and contralto.', 'A female voice between soprano and contralto.', '{}'),
  (143, 'Motet', 'Form', 'A polyphonic choral work, usually sacred and unaccompanied.', 'A polyphonic choral work, usually sacred and unaccompanied.', '{}'),
  (144, 'Neo-Classical', 'Style', 'A 20th-century style returning to Classical forms and restraint.', 'A 20th-century style returning to Classical forms and restraint.', '{}'),
  (145, 'Obbligato', 'Performance', 'An essential accompanying instrumental part, not optional.', 'An essential accompanying instrumental part, not optional.', '{}'),
  (146, 'Ornament', 'Technique', 'Decorative notes added to a melody: trills, turns, mordents.', 'Decorative notes added to a melody: trills, turns, mordents.', '{}'),
  (147, 'Passacaglia', 'Form', 'A variation form built over a repeating bass line.', 'A variation form built over a repeating bass line.', '{}'),
  (148, 'Partita', 'Form', 'A Baroque suite of dances for solo instrument.', 'A Baroque suite of dances for solo instrument.', '{}'),
  (149, 'Pastorale', 'Form', 'Music evoking rural, peaceful scenes.', 'Music evoking rural, peaceful scenes.', '{}'),
  (150, 'Cadential', 'Harmony', 'Relating to a cadence; approaching a point of harmonic resolution.', 'Relating to a cadence; approaching a point of harmonic resolution.', '{}')
ON CONFLICT (id) DO UPDATE SET
  term = EXCLUDED.term,
  category = EXCLUDED.category,
  short_definition = EXCLUDED.short_definition,
  long_definition = EXCLUDED.long_definition,
  media_links = EXCLUDED.media_links;
